### ISSUE TITLE
[1.14.4] Huge lag spikes during GC only when both Optifine and JourneyMap are installed

### ISSUE THREAD

**Issue by Neamow** [TeamJM/journeymap#181]
#### JourneyMap Version:
1.14.4-5.7.0b1

#### Forge Version:
1.14.4-forge-28.2.0

#### Optifine Version:
1.14.4_HD_U_F5

#### Describe the problem in repeatable steps:

1. Install both JourneyMap and Optifine together
2. Load world, experience large lag spikes during garbage collection

When neither are enabled, there are no issues. When only one is enabled, whether JourneyMap or Optifine, there are no issues. Only if both are enabled these issues occur.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No errors shown in the log.

**Comment by Cinahcem** [comment]
I have exactly the same problem...

**Comment by CreepyHobo** [comment]
Same issue here, please fix.

**Comment by kallezz** [comment]
Here too. I love jorneymap but as I also play with shaders almost 24/7 it is a pain...

**Comment by mysticdrew** [comment]
Does this also happen in 1.15.2?

**Comment by Neamow** [comment]
Well I just tried it, and I can't tell you, because the preview version of Optifine for 1.15.2 crashes the game before it loads, with or without JourneyMap enabled.

**Comment by mysticdrew** [comment]
I was just looking through our Alpha test reports. We had a tester that was complaining about bad FPS, though I am not sure if they had Optifine installed or not.

They said Updating forge resolved it for them. Journeymap 5.7.0b1 for 1.14.4 was built with Forge 28.2.3. Though I am not sure the minor updates would cause this issue to be fixed. 

I am about to head out of town for a week so I will not be able to look much into it until I return. 

Looking at the forge update logs, none the changes between 28.2.0 and 28.2.3 would effect journeymap in anyway but maybe Optifine because there was some graphics changes. 

I have a hard time fixing issues caused by optifine because it cannot be run in a dev environment. Previously in 1.12.2 most issues were resolved between JM and Optifine when users disabled optfine's fast render option.

**Comment by kallezz** [comment]
I tried to tweak around optifine settings turning them on/off one by one and nothing seemed to fix the spikes during carbage collection. Using latest version of forge for 14.4 (1.14.4 - 28.2.3).

**Comment by mysticdrew** [comment]
If anyone has any experience with a java profiler and can pinpoint where this is happening. Please let me know, I am not having the issue.

**Comment by John439** [comment]
If you can't reproduce the issue:

Remove the garbage collector stuff from command line, so the default one will be used. With CMS the issue is less visible, but is still there, while with the default one the things are way worse.
Increase the heap for JVM to 8GB or something like this.
Note that I know that the default GC should be avoided and 8GB is way too much. But with these settings the issue become more obvious (60+ fps and then drop to 0 instead of having 30fps without major drops). For example with these settings I have freezes that takes almost a second. And only when GC runs. If I remove Optifine the freezes disappear. Same if I remove Journey Map.

I tried to find out why but failed so far. I would say that is something related to the finalize method used by Journey Map in some classes, but why the issue doesn't reproduce without Optifine?

**Comment by John439** [comment]
Had some time to debug the issue and it seems the freezes are caused by the finalize methods. I don't know why Optifine makes things worse.

With default GC and 8GB heap:

[GC (Allocation Failure) [PSYoungGen: ... [Times: user=1.52 sys=0.17, real=0.71 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=1.17 sys=0.00, real=0.41 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=1.31 sys=0.00, real=0.44 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=1.36 sys=0.03, real=0.50 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=1.22 sys=0.00, real=0.45 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=1.20 sys=0.00, real=0.38 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=1.33 sys=0.00, real=0.46 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=1.52 sys=0.00, real=0.57 secs]

After removing the journeymap.client.model.ChunkMD.finalize method (which does nothing):

[GC (Allocation Failure) [PSYoungGen: ... [Times: user=0.75 sys=0.03, real=0.12 secs] 
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=0.59 sys=0.03, real=0.08 secs] 
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=0.75 sys=0.00, real=0.09 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=0.73 sys=0.00, real=0.09 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=0.61 sys=0.00, real=0.09 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=0.75 sys=0.00, real=0.10 secs]
[GC (Allocation Failure) [PSYoungGen: ... [Times: user=0.73 sys=0.00, real=0.10 secs]

Is few times faster. Still bad, but at least looks playable using CMS collector.
The patched version: https://we.tl/t-WMFcpbj65w (if someone wants to try it too).

There are few other finalize methods which should be removed too (probably only fist 2):
journeymap.client.model.ImageHolder.finalize()
journeymap.client.render.texture.TextureImpl.finalize()
modinfo.mp.v1.Client.finalize()
org.eclipse.jetty.util.resourceResource.finalize()

**Comment by mysticdrew** [comment]
I had to delete your link, no redistribution of our mod, especially modified ones. 

However, if anyone wants to come into our discord and test some builds. That would be the easiest solution.

**Comment by mysticdrew** [comment]
Thanks for your help with this @John439

**Comment by mysticdrew** [comment]
I have a test build with the suggestions from John, come into discord to see if this resolves your issues please.

**Comment by Traktool** [comment]
Did you think you can resolve this bug for the next update ?
Because other maps mods really sucks, Journey Map really the best

**Comment by Cinahcem** [comment]
It is true that it will be really cool that it is settled, but in the meantime I use the journey map of 1.12.2 which works very well with optifine

**Comment by RandomGgames** [comment]
Glad I found this, same issue.

**Comment by mysticdrew** [comment]
This is fixed for beta 2. Though I still have a lot of other things to address in beta 2 before release. So it may be another week or so.
