### ISSUE TITLE
[1.16] Error with Z coordinate display on Fullscreen map

### ISSUE THREAD

**Issue by WormSign** [TeamJM/journeymap#235]
Journeymap: 1.15.2-5.7.0b2
Forge:  1.15.2-forge-31.1.0

On the fullscreen map, the map coordinates of the mouse/cursor are displayed at the bottom center of the screen. The value for the Z coordinate is fundamentally wrong. As it is now on this version of Journeymap (and beta1 as well), Z values on the fullscreen map increase (get bigger) as you move your mouse from south to north. This is the opposite behavior of how the Z coordinates work in Minecraft. Again, this only pertains to the coordinates displayed at the bottom center of the screen. The player's location coordinates at the top and waypoints display the correct values.

**Comment by NickGrease** [comment]
I'll add to this since I think it's the same issue - but adding bookmarks at cursor in fullscreen map mode places the bookmark several hundred pixels above where the cursor was. Going strictly by what  coordinates are displayed (at the bottom of fullscreen map) - the bookmark is placed correctly in the Z axis and several hundred units up (north) on the X axis.

**Comment by mysticdrew** [comment]
To add to this for my reference. 

Press B or C at the mouse cursor gives the opposite Z cords in reference to the player.  -> fix in  GriderRenderer.getBlockAtPixel

**Comment by mysticdrew** [comment]
This is fixed in 5.7.1 beta 4 for 1.16.5 when it is released.
