### ISSUE TITLE
When's 1.16?

### ISSUE THREAD

**Issue by SirTwsted** [TeamJM/journeymap#253]
Any chance for a MC-v1.16+ forge version ?
As the current choices for maps are not cutting it right now.

**Comment by gdude2002** [comment]
Yes, but not yet. MCP mappings aren't encompassing enough right now - we need better mappings or we'll have to do a lot of redundant work that we'll just have to reverse later.

**Comment by SirTwsted** [comment]
aaah ok, thank for for responding.  Its very much appreciated.  :)

**Comment by WhiteSammy** [comment]
Just curious, is there a rough eta?

**Comment by gdude2002** [comment]
I'm afraid not.

>

**Comment by JRBourque** [comment]
What need to be coded in terms of MCP mapping is that another project ?

**Comment by gdude2002** [comment]
MCP's proprietary nature makes it difficult to contribute to. We have no choice but to wait for their mappings to improve - and that likely won't happen until after 1.16.2 is released.

**Comment by racinmat** [comment]
Maybe I missed something, but I thought the current way to use mappings is using MCP-Reborn, which supports minecraft up to version 1.16.3, right? https://github.com/Hexeption/MCP-Reborn
And it's on github. 
Or is there a reason why to use MCP and not MCP-Reborn, I'm missing?

**Comment by gdude2002** [comment]
MCP Reborn seems like it's probably not relevant for us, considering we have to work with Forge (which isn't really compatible with alternate mappings at the moment)

**Comment by jpgklassen** [comment]
Will older versions of JourneyMap work on Minecraft 1.16+?

**Comment by gdude2002** [comment]
No.

**Comment by JRBourque** [comment]
I just checked forge download page for 16.3 and they released a recommended version recently 34.1.0 . Are the mcp binding done in a good  enough way ?

Jean-René (JR) Bourque

**Comment by gdude2002** [comment]
I'll have to talk to mystic about it, but he's super busy atm

**Comment by imodre** [comment]
Any updates?

**Comment by gdude2002** [comment]
Afraid not

**Comment by imodre** [comment]
Hmmm... maybe some estimations about release date?

**Comment by carstorm** [comment]
Hate to be the person to ask but with the final version of MC (1.16.4) being out (until next major version 1.17), any updates on Journey Maps release?

**Comment by Snivyer1910** [comment]
what about if you move to fabric? I know it would requiere you to take new learnings but there's a lot of documentations since yarn and mixins are FOSS, also you can get help from the fabric project discord server

**Comment by gdude2002** [comment]
I would support a move to Fabric, and it's something we've talked about at length. That said, it would be a monumental undertaking — there's a whole ton of work to do in order to achieve something like that and, while it's true that a lot of the things we do could potentially be made easier via the mixin system, it's not a small job.

On the other hand, such a project would probably need to be a complete rewrite — I guess it could be done if we had the right team.

---

As for the politics of the issue, I'm actually one of the moderators on the Fabric Discord server (come say hi sometime!). Fabric provides an environment that is far less developer-hostile and far more future-proof, and I would support anyone that wishes to move to it.

**Comment by MokahTGS** [comment]
Please do not move to Fabric...there are tones of mods on 1.164 Forge (we have over 200 in our modpack) and Journey Map is the superior minimap mod.

It is very frustrating that Fabric/Forge is splitting the modding community.

**Comment by gdude2002** [comment]
It was always going to happen. The solution is definitely not trying to make developers stick to the... very broken status quo, though. What we really need are projects like Patchwork and Yarnforge that make writing mods that target both modloaders easier (or simply convert mods between each), but we're a long way off.

That said, a mod like JourneyMap would be _far_ easier to maintain using Fabric's mixin system. Either way though, nobody really has any time to work on it, and we're unable to bring any more people in without @techbrew-mc's approval either - not a lot can be done right now.

**Comment by XilefTech** [comment]
aren't there also solutions for mixin in Forge (I thought I had seen one or two mods about it on curseforge)

Also, sorry to be the annoying person to ask again, but any chance of an eta for a 1.16.4 version by now?

**Comment by gdude2002** [comment]
99% of our problems are caused by:

* Current developers not having time to work on JM
* Copyright holding developer being absent and unwilling to open-source the mod

We never provide ETAs unless we're close to a release - at this point we'll likely be skipping 1.16.

Regarding mixins, yes, they're possible in Forge, but Lex hates them so much that you get banned for talking about that in most parts of the Forge community.

**Comment by XilefTech** [comment]
> at this point we'll likely be skipping 1.16

that's sad to hear. JM was always the best Map mod out there.... What is the best alternative then?

**Comment by gdude2002** [comment]
Personally I use Just Map for Fabric. Not sure what the current meta is like with Forge.

**Comment by XilefTech** [comment]
did the copyright holding developer give any reason for not open-sourcing the mod?

**Comment by gdude2002** [comment]
The last time I asked, it was because the project is basically a bunch of jenga code - it's a seven year old project that's never had a full rewrite, and he wanted to rewrite it before open-sourcing it so that the code would be at a standard he was happy with.

Unfortunately, since then, he's been unavailable.

**Comment by MokahTGS** [comment]
Currently Xaero's World/Mini Map is the default Forge map mod for 1.16.4.

**Comment by UltraBlackLinux** [comment]
Maybe consider waiting for Patchwork to start 1.16 ;)

**Comment by mysticdrew** [comment]
1.16 version is out and available to download on curse.
