### ISSUE TITLE
[SUGGESTION] Increase the minimum zoom

### ISSUE THREAD

**Issue by usnet-000** [TeamJM/journeymap#257]
I think that the minimum zoom could be deceased, as this would be a big qol improvement on large servers where the current min zoom barely shows anything.

**Comment by gdude2002** [comment]
This is currently not a possibility ingame, but the webmap is able to do it - so try that.

**Comment by usnet-000** [comment]
Two things:
Firstly, the web map is not a huge improvement to the ingame map.
Secondly, I can think of a way to implement it without changing much of the code: by creating multiple saved maps for different zoom sizes (which could theoretically be used to show the entire world).

**Comment by gdude2002** [comment]
We have had some ideas on it, but performance is a big concern on all fronts. Browsers are much better suited to this kind of work.

What don't you like about the webmap?

**Comment by usnet-000** [comment]
It’s barely able to zoom out more than the ingame map

**Comment by usnet-000** [comment]
And how does saving multiple map files change performance much, in addition this could be a setting, ie. “How many Zoom levels do you want to store?”

**Comment by gdude2002** [comment]
You can zoom out to two extra levels - it's currently locked to that because of the massive performance hit required, but I am considering making it configurable at some point.

Also, you're suggesting generating multiple sets of tiles - that's going to have a multiplicative effect on performance. Most players are not running machines that will handle that too well - we're thinking about doing that at the rendering level as a first preference.

If you wish to discuss this further, please feel free to [join us on Discord](https://discord.gg/eP8gE69[]()) - it's easier to have an active discussion there.
