### ISSUE TITLE
Fabric?

### ISSUE THREAD

**Issue by derabzockerHD** [TeamJM/journeymap#275]
Can you make a version for fabric?

**Comment by gdude2002** [comment]
It's something we're thinking about, but we don't want to have to maintain two codebases - for now, we'll focus on getting the Forge version up to date, and we'll see where things go.

There's also [a fair bit of controversy happening with Fabric right now](https://gserv.me/minecraft-and-subtle-bigotry/).

**Comment by RDKRACZ** [comment]
>There's also a fair bit of controversy happening with Fabric right now.

So there is [Quilt](https://quiltmc.org/faq/) - Fabric fork without bad organization, etc. It's, and will be, for a long time fabric compatible.

What about porting to Quilt/Fabric using [Architectury API](https://github.com/architectury/architectury-api)?

**Comment by sasha066** [comment]
> There's also [a fair bit of controversy happening with Fabric right now](https://gserv.me/minecraft-and-subtle-bigotry/).

Looks just like a Forge fan trying to crap Fabric.

**Comment by BrainStone** [comment]
> > There's also [a fair bit of controversy happening with Fabric right now](https://gserv.me/minecraft-and-subtle-bigotry/).
> 
> Looks just like a Forge fan trying to crap Fabric.

Have you read the article?  
Like no offense but reading anything more than 2 paragraphs should make it abundantly clear that this article has substance is a lot more than a "Forge fan trying to crap Fabric". I mean the mere existence of Quilt should be evidence enough that there had been some serious shit. Else people don't just break off and make their own version of the same.

And I have personally made unpleasant contact with the Fabric community. Though more of an elitism problem than anything else. So holding off adoption due to the multiple controversies and issues going on over there is more than justified.

**Comment by gdude2002** [comment]
> > There's also [a fair bit of controversy happening with Fabric right now](https://gserv.me/minecraft-and-subtle-bigotry/).
> 
> Looks just like a Forge fan trying to crap Fabric.

Hey, as the person that actually wrote that article, I take the implication that I am a [Forge fan](https://user-images.githubusercontent.com/204153/125080659-fbecb680-e0bc-11eb-82fc-3c64a96a1521.png) as a personal insult. Anyone that takes ten minutes to do some research will find out I'm much more of a [Fabric fan](https://user-images.githubusercontent.com/204153/125080732-1161e080-e0bd-11eb-8592-e7579f21b337.png), even with some cursory research.

All jokes aside though, trying to bundle up everyone with complaints about Fabric into "yelling forge fans" as is so often seen is ridiculous. The issues presented in that article - and that have become apparent since that article was published - are far, far bigger than any sense of entitlement you may have about which mod-loader a mod should use. 

People like that try to trivialize everything into tribalism and lack of convenience legitimately get people killed - or, at the very least, burn mod developers out to the point where they don't want to work with their users anymore.
