### ISSUE TITLE
Problem Jorneymap

### ISSUE THREAD

**Issue by DANIYALWORLD** [TeamJM/journeymap#291]
#### Instructions for Submitting an Issue

---
  
#### JourneyMap Version:

Example: journeymap-1.15.2-5.7.0

#### Forge Version:

Example: forge-1.15.2-31.2.49

#### Describe the problem in repeatable steps:

1.I play with a friend on hamachi a friend has a button to teleport to the label and I only have a button to search, turn off labels, delete, chat, if I create a world then I have a button to teleport to the label what to do it?

**Comment by mysticdrew** [comment]
you have provided no logs, though it is likely your friend is an op and you are not.

**Comment by DANIYALWORLD** [comment]
mysticdrew and how to give out an op on a local network if we play not on the server but through hamachi 👀

**Comment by DANIYALWORLD** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/83093474/115972988-86138d00-a55a-11eb-8802-600c15ccdc33.png)

**Comment by mysticdrew** [comment]
I don't know what hamachi is, but if are playing a lan game(which sounds like you are), there are some oddities with journeymap for minecraft 1.14 and 1.15 and lan games. 
Your best bet is to set up a dedicated server.

**Comment by BrainStone** [comment]
Hamachi is old school P2P VPN

**Comment by mysticdrew** [comment]
I forgot to ask @DANIYALWORLD did you enable waypoint teleporting in the server admin screen?

After your world is open to lan, press J, press O, bottom right will be a "Server Admin" button, click it then enable waypoint teleporting. 

If that does not work, there will be no fixing coming because we are only working on the 1.16.5 version and I verified that lan issues are resolved.
