### ISSUE TITLE
High CPU usage while using JourneyMap

### ISSUE THREAD

**Issue by YarinQuapi** [TeamJM/journeymap#393]
#### Describe the problem in repeatable steps:
High activity, up to 9.84% of CPU usage per tick is used by JourneyMap, that high CPU usage leads to problems with garbage collection which causes lag spikes in the end.
now, obviously, JourneyMap isn't the only mod I use, however, 9.84% per tick (over a 10 minute period of testing) is a lot of CPU usage for a mod with a "minimal" effect on gameplay. I would recommend checking into it

1. Launch the game (and open a world, obviously)
2. Profile all activity using Spark
3. After a while upload the activity and look at the results.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No errors

(if you want the entire heap, send me a message)
![journeymap-highcpu](https://user-images.githubusercontent.com/41652571/152700899-e0833986-b841-4808-ad08-f013f4adf0fb.png)

[journeymap.log](https://github.com/TeamJM/journeymap/files/8011212/journeymap.log)

**Comment by mysticdrew** [comment]
How does it compare with your current mods and beta11?
How does it look with only journeymap and no other mods?

**Comment by YarinQuapi** [comment]
1. didn't understand the first question
2. it is not only journeymap, the GUI performance monitoring tab is open
3. https://spark.lucko.me/Xc2zAGnsRK

**Comment by mysticdrew** [comment]
1. Can you revert to beta11 and see if it has similar cpu issues? 
2. Can you run with only journeymap and spark and see if the issue persists with beta13.

**Comment by YarinQuapi** [comment]
1. Using beta11 seemed to increase the usage from 9.84% to 10.25%
2. I sadly don't have the time currently to do that but I could try that tomorrow possibly

link to updated spark profile: https://spark.lucko.me/MJt24LNmnN

**Comment by mysticdrew** [comment]
I find that strange that switching to beta11 made it worse but that is a small amount, so probably insignificant. 

If you could test tomorrow, that would be ideal so we have a baseline to see if there is a mod interaction happening.
Feel free to join our discord, it may be easier to discuss this and work through it on discord.

**Comment by YarinQuapi** [comment]
After a quick test using beta13 alone, it went down to as low as 3.67%, a quick guess of mine is it's having a hard time retrieving modded textures or dealing with a large number of mods.
I also joined the discord.

**Comment by mysticdrew** [comment]
I published beta14 with some optimizations. 
Most of the high cpu usages in that spark is normal and they are the minecraft rendering engine.
If you had mods that were rendering polygons on the map, beta14 did a lot to optimize it significantly. Check it out and see. Also you need to update your spark mod as it missing some details that could be useful.

**Comment by glindsey** [comment]
I've been trying to track down a similar problem that just started happening with my 1.18.1 instance -- garbage collection freezes occurring every few seconds and lasting anywhere from a couple dozen milliseconds in most cases to two or three seconds at worst. I just confirmed that the issue is present in beta13, but absent in beta11; it looks like beta13 uses _way_ more memory than beta11, and that quickly overwhelms my memory and triggers recurring GC that seizes up the client.

(Disclaimer: I'm a veteran coder, but not in Java or any other language that uses a GC. Please forgive me if I'm getting any technical details wrong.)

Context: 
I'm running 116 mods, Forge 39.0.75, MC 1.18.1. 
The server is running on a Linux Mint system, older Core i5 (don't know exactly what gen), 16GB RAM. It exhibits no problems running any version of JourneyMap.
The client is on a Windows 10 system, older Core i7 (6th gen, I think?), 16GB RAM.

Beta11: Looking at F3 debug, when I just run around the world aimlessly (in an area already mapped), I'll see memory usage routinely hit somewhere in the 40-50 percent range before collection occurs. When GC occurs (according to Spark's GC monitor), it's almost unnoticeable.

Beta13: Doing the same thing, memory usage climbs to 75 to 80 percent, and sometimes hits the 90s. `sparkc gcmonitor` shows GC occurring a lot more frequently, maybe every two or three seconds vs the ten or more with beta11, and when it does happen, there's almost always a noticeable freeze in the client.

My guess is that the region data caching changes you mentioned in the beta13 changelog are contributing to the problem. Ugh, memory management is such a nightmare, isn't it?

In any case, I can provide further technical details if it will help you, just let me know what you need. JourneyMap is absolutely one of the must-have mods for my daughter and I, and I really appreciate all the work you put into it.

**Comment by mysticdrew** [comment]
> 



> I've been trying to track down a similar problem that just started happening with my 1.18.1 instance -- garbage collection freezes occurring every few seconds and lasting anywhere from a couple dozen milliseconds in most cases to two or three seconds at worst. I just confirmed that the issue is present in beta13, but absent in beta11; it looks like beta13 uses _way_ more memory than beta11, and that quickly overwhelms my memory and triggers recurring GC that seizes up the client.
> 
> (Disclaimer: I'm a veteran coder, but not in Java or any other language that uses a GC. Please forgive me if I'm getting any technical details wrong.)
> 
> Context: I'm running 116 mods, Forge 39.0.75, MC 1.18.1. The server is running on a Linux Mint system, older Core i5 (don't know exactly what gen), 16GB RAM. It exhibits no problems running any version of JourneyMap. The client is on a Windows 10 system, older Core i7 (6th gen, I think?), 16GB RAM.
> 
> Beta11: Looking at F3 debug, when I just run around the world aimlessly (in an area already mapped), I'll see memory usage routinely hit somewhere in the 40-50 percent range before collection occurs. When GC occurs (according to Spark's GC monitor), it's almost unnoticeable.
> 
> Beta13: Doing the same thing, memory usage climbs to 75 to 80 percent, and sometimes hits the 90s. `sparkc gcmonitor` shows GC occurring a lot more frequently, maybe every two or three seconds vs the ten or more with beta11, and when it does happen, there's almost always a noticeable freeze in the client.
> 
> My guess is that the region data caching changes you mentioned in the beta13 changelog are contributing to the problem. Ugh, memory management is such a nightmare, isn't it?
> 
> In any case, I can provide further technical details if it will help you, just let me know what you need. JourneyMap is absolutely one of the must-have mods for my daughter and I, and I really appreciate all the work you put into it.

hope into our discord. I have some test builds for 1.18.1 that is MUCH improved over beta13. But still some small issues I need to find and resolve.

**Comment by glindsey** [comment]
Ha, I just saw that! I've done so, and will keep an eye on it.

**Comment by mysticdrew** [comment]
beta15 is published to curseforge.
