### ISSUE TITLE
Order of coordinate components is not consistent within Journeymap UI and dialogs

### ISSUE THREAD

**Issue by TheRealWormbo** [TeamJM/journeymap#422]
#### JourneyMap Version:

`1.18.1-5.8.0beta15`

#### Forge Version:

`1.18.1-39.1.2`

#### Describe the problem in repeatable steps:

1. Set all map presets to coordinate ordering X/Y/Z, i.e. the same order Minecraft and most other mods use.
2. Open the dialog to create a new waypoint or to edit an existing one. 
3. Get confused by the swapped Y and Z input boxes.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

(n/a)

**Comment by mysticdrew** [comment]
The text boxes are clearly labeled, and it is intentional that they are in the order that they are in. 
They will not be moved as they have been in this order for the last 10 years, I think it may cause confusion to switch them up now. 
It may change with the waypoint revamp in the future.

**Comment by 0xallie** [comment]
Just because this mod has had it like this for 10 years doesn't mean the current behavior won't confuse players, especially when trying to copy X/Y/Z coordinates from a wiki page or something.

If you think some players may prefer X/Z/Y for waypoint creation but X/Y/Z for the map, why not make it a separate toggle?

**Comment by Esprits** [comment]
I know this is an old issue and that it's been closed, but I'd really appreciate the toggle suggestion ghost has brought up.
I've started using this mod in the past few months, and I have always been used to viewing and sharing my coords in the XYZ format and would appreciate it being an option instead of having to get used to the XZY format even though it's easy to do.

It's simply a question of thinking of what the users would want.

**Comment by jwols123** [comment]
I agree with this. As someone who uses Journeymap fairly often and enjoys it, it's quite a curveball every time I have to reverse it - especially since I'm incredibly used to X/Y/Z for general chatting.
I would appreciate it if a setting could at least be made to do this.

**Comment by mysticdrew** [comment]
This has been in 6.0.0 for 1.21.1+ for quite some time. 

![Image](https://github.com/user-attachments/assets/1fb38bc7-8499-4779-85ed-a2f0f7a4aa61)
