### ISSUE TITLE
[Suggestion] Allow for saving maps based on IP of server host

### ISSUE THREAD

**Issue by BuggyAl** [TeamJM/journeymap#455]
Instead of the following:
`Using Server Seed Hash: "MyServer", seedId: "MyServer_id_123123"` 
`Using World ID (from plugin): worldId: "MyServer~123-123-123"`
add an option to save based on the IP of the server host.
`None : SeedHash : IP`

**Comment by mysticdrew** [comment]
This is completed for the next major release. 

If the server uses WorldID that takes precedence. 
If not, you can use Ip, Seed, or both ip and seed. 
Ip format  is ip/ip:port. This is due to how socket address work example: `192.168.0.1/192.168.0.1:8080`
examples:
`worldname_ip_192~168~0~1~192~168~0~1~25565` 
`worldname_id_123413241234` 
And with IP and MultiWorld support checked
`worldname_id_123413241234_ip_192~168~0~1~192~168~0~1~25565`

we replace any special characters with `~`

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
