### ISSUE TITLE
Possible conflict with Origins mod?

### ISSUE THREAD

**Issue by fabmm** [TeamJM/journeymap#472]
#### JourneyMap Version:

`journeymap-1.18.2-5.8.5-forge`

#### Forge Version:

`40.1.31`

#### Describe the problem in repeatable steps:

I've been noticing lots of memory lag and log spam from Journeymap when on the Origins selection menu.. could be a possible conflict?
https://www.curseforge.com/minecraft/mc-mods/origins-forge this mod gives the user a selection menu at the start of a world to select their "origin/race" and at that menu jm goes crazy... starts lagging the hell out of the game and spamming the log
that message i sent gets sent thousands of times

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

https://paste.ee/p/PwC2k

**Comment by mysticdrew** [comment]
Please create a similar issue on their tracker and add the link to this one

**Comment by fabmm** [comment]
> Please create a similar issue on their tracker and add the link to this one

https://github.com/EdwinMindcraft/origins-architectury/issues/194

**Comment by EdwinMindcraft** [comment]
Unless I missed something drastic, Origins and it's dependencies do not hook into the window size fields, which are created by Blaze3D and represent the GLFW window's width and height.
If I missed something please tell me, but I don't see any bug in origins affecting that specific piece of code.

**Comment by mysticdrew** [comment]
@fabmm 
is this still an issue for you with the latest version of Origins? What version were you using when this issue happened?

So, my indev version which is much different that 5.8.5, I loaded up [[1.18.2] Origins Forge 1.5.0.2](https://www.curseforge.com/minecraft/mc-mods/origins-forge/files/3892104) and my dev environment blew up. Probably due to jnj. @EdwinMindcraft any suggestions?

Then tried [[1.18.2] Origins Forge 1.4.1.4](https://www.curseforge.com/minecraft/mc-mods/origins-forge/files/3847281) and no issues at all. If you wish to try my indev version, please come to our discord and say hi. 

Looking at your issue on the origins tracker, you have `origins-classes-forge-1.1.5.1` I don't see that version on curseforge.

**Comment by mysticdrew** [comment]
Closing as there has been no response.
