### ISSUE TITLE
[Feature Request] Automatic Waypoint Coloring

### ISSUE THREAD

**Issue by codewarrior0** [TeamJM/journeymap#51]
Context: Mods such as GregTech, Immersive Engineering, or Geolosys will add *mineral veins* to the world in specific locations. A savvy player will mark these veins using JourneyMap waypoints.

When marking a waypoint that has a name identical to another waypoint, JourneyMap should automatically  choose the color used for the other waypoint. For example, if I create a waypoint named "Gold" and color it yellow, the next time I go to create a waypoint and name it "Gold", it should choose the same yellow color after I have typed "Gold" into the waypoint name field.

**Comment by ryankhart** [comment]
This is an interesting idea, but what if the end user doesn't agree with the automatic color rules?

I think the idea could be improved if there was a rule system to allow the player to create their own rules for automatic coloring, and tuck that menu in the advanced settings section so that it doesn't get in the way or overwhelm casual players, where it can safely be ignored.

**Comment by mysticdrew** [comment]
We would likely get so many complaints about this "why are all my waypoints blue?" This is likely not something we will do. However, waypoints can be created via plugins. You could use our plugin system form this.
