### ISSUE TITLE
[1.19.2] World loading crashes

### ISSUE THREAD

**Issue by oninbo** [TeamJM/journeymap#511]
#### JourneyMap Version:

`1.19-5.8.5`

#### Forge Version:

`1.19.2-43.1.34`

#### Describe the problem in repeatable steps:

1. Install JourneyMap and [The Lost Cities](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities) mods
2. Create a world
3. Open the world that was created in the previous step

**Expected behavior:** world is loaded and playable.
**Actual behavior:** game crashes.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`: none

[Issue in The Lost Cities repository](https://github.com/McJtyMods/LostCities/issues/492)

#### Game logs
[debug.log](https://github.com/TeamJM/journeymap/files/9739619/debug.log)
[latest.log](https://github.com/TeamJM/journeymap/files/9739620/latest.log)

**Comment by gdude2002** [comment]
Since you didn't fill out the issue template properly, I've taken the liberty of adding the JM and Forge versions for you based on your logs.

However, it seems to me that you're using a version of JM meant for 1.19, and you're playing Minecraft 1.19.2. You should try again with a version of JourneyMap intended for 1.19.2.

**Comment by mysticdrew** [comment]
Straight from the curseforge page
![image](https://user-images.githubusercontent.com/5459941/194715758-c694ee21-7b8a-46d1-a2fa-fff38210dc29.png)
