### ISSUE TITLE
[Feature Request] Entity Naming

### ISSUE THREAD

**Issue by CrocodileWithAHat** [TeamJM/journeymap#520]
Not exactly an issue however, the option that says "Show Entity Names" Should show nametagged animals on the map for the 5.8.5 version of the minimap.

**Comment by mysticdrew** [comment]
![image](https://user-images.githubusercontent.com/5459941/200994353-c8250c46-f211-4b30-85a2-382fcfd21268.png)
Currently, per the code this was implemented for only custom nbt tagged named entities. I have no idea why it was done this way. 
It should be made so that pets show up also and other tagged npcs. Not just special npc from rpg mods as the current implementation is.

**Comment by mysticdrew** [comment]
This is completed for the next Major release. 
New options for entities and a hotkey to enable disable on the fly. 
And you can hold Tab to show icons and names. 
Will close once this is released.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
