### ISSUE TITLE
[Suggestion] Retain waypoint sorting data on game close

### ISSUE THREAD

**Issue by taj1994** [TeamJM/journeymap#526]
As discussed on the Discord server, waypoint sorting data should be saved after the game closes, and currently doesn't
![image](https://user-images.githubusercontent.com/1844822/203020841-d6ca039d-3af5-45a3-9bf5-db71b44c0082.png)
If it were up to me, I'd also have it sort by distance by default like it was back in 1.12.2 (maybe more recently, but this was gone by 1.16), but as long as it saves the sorting data after it's set by the player, that'll be good enough

**Comment by mysticdrew** [comment]
> If it were up to me, I'd also have it sort by distance by default like it was back in 1.12.2
This is the case and has not changed. 
What has changed since 1.12.2 was that sorting stayed if you closed the window. So if you clicked date, it would stay date until you closed minecraft or clicked distance. 

Anyways, this is added for the next major release. Sorting State is saved in a config now, so it will retain on MC restart.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
