### ISSUE TITLE
[Feature Request]: theme color pickers in the the gui screen

### ISSUE THREAD

**Issue by asphyxia1337** [TeamJM/journeymap#596]
### Describe the new feature.

cool and simple for custom themes.

### Images

![image](https://github.com/TeamJM/journeymap/assets/80584861/9f5d579d-f970-4dd2-ae96-326c535d3c30) like this
![image](https://github.com/TeamJM/journeymap/assets/80584861/c4cd8629-8498-41f6-89c2-8e69a487efc8) or this idk

**Comment by mysticdrew** [comment]
I have some plans for this, not sure if it will make it in to 6.0, mostly likely not as it would be a huge overhaul. 

I want to make all the UI use the theme system, currently only the fullscreen map buttons and minimap do, no other screens/buttons. 

We will likely have a theme overhaul update post 6.0 release to move most of the theme creation to a user interface instead of manually editing json files.

**Comment by mysticdrew** [comment]
new color picker has been added. 
![image](https://github.com/user-attachments/assets/448b244d-86ca-432d-9535-b34c29e5589e)
