### ISSUE TITLE
[Bug]: Shift+Tab does not move backwards in input fields

### ISSUE THREAD

**Issue by ghost** [TeamJM/journeymap#638]
### What happened?

When using Shift+Tab, e.g. on the create waypoint screen, it simply moves to the next input field like Tab. It should match the general user expectation and move to the previous input field, which is better for accessibility as well, not having to navigate through all fields just to get back to the previous one.

JourneyMap version: 5.9.12

### Mod Loader

Quilt

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

Not applicable

**Comment by mysticdrew** [comment]
Hmm, this was working I thought since we use the vanilla behavior for it. I did verify that it is in fact broken now. hmm. 
I will look into it, thanks for letting me know.

**Comment by mysticdrew** [comment]
I am going to hold off on the screens for 6.0. Since many of them are getting a rewrite and for example, the waypoint editor screen is so old and has so much odd stuff happening in it. It would take a lot of work to get the forward/reverse tabs to work correctly and bug free. 

Waypoint Manager and Editor are getting re-done with the waypoint refactor. We will probably tackle the other screens in 6.0 also.

**Comment by mysticdrew** [comment]
Waypoint editor has been rewritten fully in 6.0.0.beta.19 and provides this functionality. Will close when I release it

**Comment by mysticdrew** [comment]
new waypoint editor is live now with 1.21-6.0.0-beta.19 release is in progress
