### ISSUE TITLE
[Bug]: Two things, both related with visual mapping

### ISSUE THREAD

**Issue by ElEricua** [TeamJM/journeymap#660]
### What happened?

Hi everyone, I logged into an old server I used to play where I had terriotories mapped with journeymap, and after I loaded the world, I see this in my minimap (see image n°1), and then in the fullscreen map this (see image n°2), it keeps "erasing" the map as I move.

And the second issue I have (had), but never bothered me that much as I could still play so I didnt reported it, is that sometimes it "doesnt map" zones under a tree for example (see image n°3).
![ajebgfouysbbjsxkbv](https://github.com/TeamJM/journeymap/assets/52611128/e55fe48b-31f6-47df-b832-96291a08243e)
![akjsbdfojhbcxkg](https://github.com/TeamJM/journeymap/assets/52611128/c50630d4-767b-4815-9b3b-c8bea5d6351f)
![dwacyjnulkhhgv](https://github.com/TeamJM/journeymap/assets/52611128/71046e7d-c132-4384-b50a-39bf7ae38887)

### Mod Loader

Forge

### Minecraft Version

1.16.5

### Version

5.8.5

**Comment by ElEricua** [comment]
Sorry, the images uploded as n°3 then n°2 and n°1!

**Comment by mysticdrew** [comment]
Looks like you loaded an old version into a newer version of mc. 
You will need to start your server with this command once to fix the heightmaps. 
`java -jar server.jar --forceUpgrade --eraseCache`
I recommend backing up your world before doing this. 

The problem is sometimes heightmaps break when loading old world data into a new more modern version of minecraft. Vanilla introduced a way to fix this with the command above for servers, for singleplayer worlds there is an option when you edit a world in the singleplayer menu to optimize your world and clear chunk cache.

**Comment by ElEricua** [comment]
Is there any other way to fix the heightmaps? Because Im playing a server that isnt mine (WynnCraft)

Also, what are the heightmaps? Is the solution to the problem of the trees or to the map being erased?

**Comment by mysticdrew** [comment]
No, way to regenerate the heightmaps without access to the files. 

Heightmap is how minecraft determines the max height of the world surface. We use it to to know what the surface is, there is no way to solve the issue without fixing heightmaps. 

The solution with JourneyMap to avoid using heightmaps is scanning every single possible location for a block which is a major performance hit as you could imagine.

**Comment by mysticdrew** [comment]
Sorry, not much I can do about this issue. You could suggest the fix to the server admins.
