### ISSUE TITLE
[Bug]:  journeymap causes the server to lag

### ISSUE THREAD

**Issue by Lindsaydoodle** [TeamJM/journeymap#680]
### What happened?

A bug happened! JourneyMap make lagg server
spark profiler
[WUCq5mn1jn.zip](https://github.com/TeamJM/journeymap/files/14723431/WUCq5mn1jn.zip)

No entiendo dónde mirar y cómo lo entiendo todo. Pero la sensación es realmente ruina todo journeymap por favor, sólo ayuda será muy feliz 

minecraft 1.20.1 tested on Forge legacy and Mohist resultado es el mismo

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.18

**Comment by mysticdrew** [comment]
Provide a link to spark that you get when you stop the profiling. The file you provided does not work.
![image](https://github.com/TeamJM/journeymap/assets/5459941/a0117884-74a0-4d9b-9f5c-019e4d9702a6)

**Comment by mysticdrew** [comment]
I was able to get it to work. Strange, first time it did not work, 2nd time it did. 

Anyways, there is nothing in here that points to Journeymap causing any issues.

**Comment by mysticdrew** [comment]
Looks like there was a very large spike when you teleported with JourneyMap, likely because it was to an area where chunks were not generated and that caused a couple seconds of lag due to minecraft having to generate those chunks. 
Overall your tps is fairly low. If you are teleporting all over the place really quickly, minecraft will lag as it is generating chunks. Which is what looks like what was happening. 

I will close that as there is nothing for me to fix.
Either slow down your teleporting to populate the map, or deal with slowdowns with minecraft chunk generation. This is not a journeymap issue.

**Comment by mysticdrew** [comment]
probably because you disabled everything.

**Comment by mysticdrew** [comment]
I looked through your spark profile. 
Everything causing slowdowns because of journeymap was due to teleporting and the proceeding chunk generation after the teleport. JourneyMap does very little on the server, it does not do any mapping on the server, it primarily sends permission data and player locations if enabled. 

Teleporting to waypoints uses vanilla teleporting mechanics.
