### ISSUE TITLE
[Bug]: Waypoint icons not visible while using Oculus Shaders

### ISSUE THREAD

**Issue by mbniol** [TeamJM/journeymap#750]
### What happened?

Waypoint icons are not visible when using Oculus shaders. When the shaders are off icons become visible.

Tested on Complementary Unbound 5.2.1, Complementary Unbound 5.0.1, Bliss 2.0.4

JourneyMap version: 5.10.0
Oculus version: 1.7.0
Embedium version: 0.3.24

![shaders off](https://github.com/TeamJM/journeymap/assets/73229750/85c1a8a5-7e00-494b-a9dc-a347607c5e7e)
![shaders on](https://github.com/TeamJM/journeymap/assets/73229750/055d7b51-d8c1-4d38-88c5-844a240fde51)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

other (please list)

**Comment by mysticdrew** [comment]
This is a known issue that I was not able to resolve without completely rewriting waypoints. Which wont be done, 5.10.0 is the last version of journeymap for all minecraft versions 1.20.6 and below. 
This issue is resolved in 6.0.0 for 1.21+, but it will not be backported as it would be too much work and testing that I do not have time to do.

**Comment by mbniol** [comment]
I have found a workaround. It solves the problem partially - the icons are visible but textures don't work.

Resource pack for anyone interested:
https://www.curseforge.com/minecraft/texture-packs/journeymap-invisible-waypoint-fix
